name       : gnome-python
version    : 2.28.1
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-python/2.28/gnome-python-2.28.1.tar.bz2 : 759ce9344cbf89cf7f8449d945822a0c9f317a494f56787782a901e4119b96d8
license    : LGPL-2.0
component  : programming.python
summary    : Python bindings for a few GNOME Developer Platform libraries.
description: |
    Python bindings for a few GNOME Developer Platform libraries.
builddeps  :
    - pkgconfig(bonobo-activation-2.0)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-vfs-2.0)
    - pkgconfig(gnome-vfs-module-2.0)
    - pkgconfig(ice)
    - pkgconfig(libbonobo-2.0)
    - pkgconfig(libbonoboui-2.0)
    - pkgconfig(libgnome-2.0)
    - pkgconfig(libgnomecanvas-2.0)
    - pkgconfig(libgnomeui-2.0)
    - pkgconfig(popt)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(pyorbit-2)
    - pkgconfig(sm)
setup      : |
    %waf_configure
build      : |
    %waf_build
install    : |
    %waf_install
